# Generated by Django 3.2.6 on 2021-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
